#!/usr/bin/env bash

#  Copyright (C) 2015-2020 akha, a.k.a. Alexander Kharitonov
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

echo
echo 'The Yakhont Weaver patching JARs / AARs script reference implementation.'
echo
echo 'Usage: weave _cp [_mn] [_arg], where'
echo '  _cp  - Java class path (should include Yakhont Weaver and Javassist JARs),'
echo '  _mn  - Android project module name to weave (default one is "app"),'
echo '  _arg - user-defined info to use in build.gradle while weaving JARs / AARs,'
echo '         can be accessed via project.property("yakhont_weave_arg").'
echo
echo 'Should be called from the root project directory.'
echo

if [ "$2" == "" ]; then
  YAKHONT_TO_WEAVE=app
else
  YAKHONT_TO_WEAVE=$2
fi

if [ "$3" == "" ]; then
  YAKHONT_ARG=
else
  YAKHONT_ARG=-Pyakhont_weave_arg=$3
fi

# set Yakhont Weaver tmp dir (by default it's a current one)
# export YAKHONT_WEAVER_TMP_DIR=...

# init weaving script
java -cp $1 akha.yakhont.weaver.Weaver init

# make class map and build temp application (just to compile your code)
./gradlew --configure-on-demand $YAKHONT_ARG $YAKHONT_TO_WEAVE:clean $YAKHONT_TO_WEAVE:build

# weave JARs / AARs (with your application's code just compiled); 'true' enables debug output to console
java -cp $1 akha.yakhont.weaver.Weaver weave true

# build final application (with already weaved JARs / AARs)
./gradlew --configure-on-demand              $YAKHONT_TO_WEAVE:clean $YAKHONT_TO_WEAVE:build

# restore weaved JARs / AARs
java -cp $1 akha.yakhont.weaver.Weaver restore

# cleanup
java -cp $1 akha.yakhont.weaver.Weaver cleanup

# unset YAKHONT_WEAVER_TMP_DIR
